-- MySQL Script generated by MySQL Workbench
-- Sat Dec  9 11:44:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecology
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecology` ;

-- -----------------------------------------------------
-- Schema ecology
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecology` DEFAULT CHARACTER SET utf8 ;
USE `ecology` ;

-- -----------------------------------------------------
-- Table `ecology`.`places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecology`.`places` ;

CREATE TABLE IF NOT EXISTS `ecology`.`places` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecology`.`pollutants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecology`.`pollutants` ;

CREATE TABLE IF NOT EXISTS `ecology`.`pollutants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `VMV` DOUBLE NULL,
  `class` INT NOT NULL,
  `GDV` DOUBLE NULL,
  `tax` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecology`.`emissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecology`.`emissions` ;

CREATE TABLE IF NOT EXISTS `ecology`.`emissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emissionVolume` VARCHAR(45) NULL,
  `places_id` INT NOT NULL,
  `pollutants_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emissions_places_idx` (`places_id` ASC),
  INDEX `fk_emissions_pollutants1_idx` (`pollutants_id` ASC),
  CONSTRAINT `fk_emissions_places`
    FOREIGN KEY (`places_id`)
    REFERENCES `ecology`.`places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emissions_pollutants1`
    FOREIGN KEY (`pollutants_id`)
    REFERENCES `ecology`.`pollutants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
